#!/usr/bin/env python3
"""
Deterministic assembler for docs/capability-matrix.md.

Reads the per-use-case section files written by the `agents/capability_matrix_{uc}.exs`
section agents, concatenates them in a fixed order, and computes the entire derived
block — Overlap Report and Summary — by counting the rows of the sections' own
Agents/Scripts tables. No LLM is involved in this step (BL-067): every claimed value
is counted, not asserted.

Derived values and their rules:
  Summary counts        — agent/script table row count per section; totals are sums
  Unique tools          — backtick-delimited tokens of each Tools cell, first-appearance
                          order; a Tools cell with no backticks is taken whole as one
                          entry (e.g. "MCP servers (corpus_search, lattice)")
  Identical tool sets    — agents grouped by tool-SET equality (order-insensitive),
                          groups of >= 2, largest group first
  Script name overlaps  — a script row name appearing in more than one section

Section content is pasted verbatim except where a curated override replaces a cell
(BL-068). `docs/capability-matrix-overrides.json` is the durable home for hand-written
text the section agents would otherwise reword away — it is committed, the sections are
not. Overrides are merged into the section's own table rows *before* anything is counted,
so the emitted table and the derived block still agree. An override that matches no row
fails the run rather than silently dropping the curation it was written to protect.

Usage:
  python3 scripts/assemble_matrix.py [--sections-dir DIR] [--output FILE] [--overrides FILE]

Exit codes:
  0 — matrix written from a complete set of sections, every override applied
  1 — matrix written but partial (a section file was missing), an override matched
      no row, or the output could not be written
"""

import argparse
import json
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------------- #
# Repo layout                                                                  #
# --------------------------------------------------------------------------- #

SCRIPT_DIR    = Path(__file__).parent.resolve()
REPO_ROOT     = SCRIPT_DIR.parent
SECTIONS_DIR  = REPO_ROOT / "docs" / ".sections"
OUTPUT_MD     = REPO_ROOT / "docs" / "capability-matrix.md"
OVERRIDES_JSON = REPO_ROOT / "docs" / "capability-matrix-overrides.json"

# Explicit section order — NOT directory order. (key, summary-table label)
SECTIONS = [
    ("payslip",     "payslip"),
    ("drive",       "drive"),
    ("email",       "email"),
    ("api_tenant",  "api/tenant"),
    ("api_gateway", "api/gateway"),
    ("provenance",  "provenance"),
    ("docbuilder",  "docbuilder"),
    ("cloudcost",   "cloudcost"),
    ("eduloka",     "eduloka"),
]

TITLE       = "# Aetheris-Agents — Capability Matrix"
GENERATED_BY = (
    "_Generated by the `agents/capability_matrix_*.exs` section agents + "
    "`scripts/assemble_matrix.py` (sprint case `capability_matrix`). Re-run to update._"
)

BACKTICKED = re.compile(r"`([^`]+)`")

WARNINGS: list[str] = []


def _warn(message: str) -> None:
    """Record a warning and echo it to stderr."""
    WARNINGS.append(message)
    print(f"[WARN] {message}", file=sys.stderr)


# --------------------------------------------------------------------------- #
# Parsing                                                                      #
# --------------------------------------------------------------------------- #


def _table_rows(lines: list[str], heading: str) -> list[tuple[int, list[str]]]:
    """Return `(line index, cells)` for the data rows of the table under `heading`.

    A row is every pipe line after the `|---|` separator, up to the first line
    that is neither blank nor a pipe line. Cells are stripped; leading/trailing
    empty cells from the pipe delimiters are dropped. The line index is what lets
    a curated override replace a cell in place (see `apply_overrides`).
    """
    rows: list[tuple[int, list[str]]] = []
    seen_heading = False
    seen_separator = False

    for index, line in enumerate(lines):
        stripped = line.strip()

        if stripped.startswith("#"):
            if seen_heading:
                break
            seen_heading = stripped == heading
            continue

        if not seen_heading:
            continue

        if not stripped:
            if seen_separator:
                break
            continue

        if not stripped.startswith("|"):
            break

        cells = [c.strip() for c in stripped.strip("|").split("|")]

        if not seen_separator:
            if all(set(c) <= set("-: ") and c for c in cells):
                seen_separator = True
            continue

        rows.append((index, cells))

    return rows


def parse_tools(cell: str) -> list[str]:
    """Tools named in a Tools cell, in cell order.

    Backticked tokens are the tools. A non-empty cell with no backticks is a
    prose capability (e.g. "MCP servers (corpus_search, lattice)") and counts
    as a single entry — dropping it would understate the tool surface.
    """
    tools = BACKTICKED.findall(cell)
    if tools:
        return [t.strip() for t in tools]
    cell = cell.strip()
    return [cell] if cell else []


def parse_section(key: str, label: str, text: str) -> dict:
    """Parse one section file into its agent and script rows."""
    lines = text.rstrip().splitlines()

    agent_rows  = _table_rows(lines, "### Agents")
    script_rows = _table_rows(lines, "### Scripts")

    if not agent_rows:
        _warn(f"{key}: no rows found under '### Agents'")
    if not script_rows:
        _warn(f"{key}: no rows found under '### Scripts'")

    agents = [
        {
            "line":  index,
            "cells": cells,
            "file":  cells[0],
            "label": cells[1] if len(cells) > 1 else "",
            "tools": parse_tools(cells[2] if len(cells) > 2 else ""),
        }
        for index, cells in agent_rows
    ]
    scripts = [
        {"line": index, "cells": cells, "name": cells[0]} for index, cells in script_rows
    ]

    return {
        "key":     key,
        "label":   label,
        "lines":   lines,
        "agents":  agents,
        "scripts": scripts,
        "present": True,
    }


def load_sections(sections_dir: Path) -> list[dict]:
    """Load every section in SECTIONS order; missing sections are placeholders."""
    loaded = []

    for key, label in SECTIONS:
        path = sections_dir / f"{key}.md"
        if not path.is_file():
            _warn(f"section file missing: {path} — matrix will be partial")
            loaded.append(
                {
                    "key":     key,
                    "label":   label,
                    "lines":   [f"## {label}", "", "_Section not available._"],
                    "agents":  [],
                    "scripts": [],
                    "present": False,
                }
            )
            continue
        loaded.append(parse_section(key, label, path.read_text(encoding="utf-8")))

    known = {f"{key}.md" for key, _ in SECTIONS}
    if sections_dir.is_dir():
        for extra in sorted(p.name for p in sections_dir.glob("*.md")):
            if extra not in known:
                _warn(f"section file not in SECTIONS, ignored: {sections_dir / extra}")

    return loaded


# --------------------------------------------------------------------------- #
# Curated overrides — applied BEFORE anything is counted                       #
# --------------------------------------------------------------------------- #


def load_overrides(path: Path) -> dict | None:
    """Load the curated-cell overrides.

    Returns `{}` when the file is absent (a repo may legitimately curate nothing) and
    `None` when it is present but unreadable — that case drops *every* override at once,
    which is the failure this file exists to prevent, so the caller fails the run.
    """
    if not path.is_file():
        _warn(f"overrides file missing: {path} — sections used exactly as generated")
        return {}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _warn(f"overrides file is not valid JSON ({path}): {exc} — all curation dropped")
        return None


def _row_line(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _apply_cell(row: dict, lines: list[str], column: int, value: str) -> None:
    """Replace one cell of a parsed row, in the row's own source line."""
    cells = list(row["cells"])
    while len(cells) <= column:
        cells.append("")
    cells[column] = value
    row["cells"] = cells
    lines[row["line"]] = _row_line(cells)


def apply_overrides(section: dict, overrides: dict) -> list[str]:
    """Merge curated cells over the generated ones. Returns unmatched override keys.

    Overrides are applied to the section's own table rows *before* any derived value
    is computed, so the emitted table and the derived block still agree — claimed ==
    counted holds exactly as it did without overrides.

    Agent keys are the agent file name, or `file::label` when one file contributes
    several rows to a section (an OrbConfig with several RunConfigs).
    """
    entry = overrides.get(section["key"], {})
    agent_overrides  = entry.get("agents", {})
    script_overrides = entry.get("scripts", {})
    matched: set[str] = set()

    for agent in section["agents"]:
        for key in (f"{agent['file']}::{agent['label']}", agent["file"]):
            if key not in agent_overrides:
                continue
            matched.add(key)
            fields = agent_overrides[key]
            if "label" in fields:
                _apply_cell(agent, section["lines"], 1, fields["label"])
                agent["label"] = fields["label"]
            if "tools" in fields:
                _apply_cell(agent, section["lines"], 2, fields["tools"])
                agent["tools"] = parse_tools(fields["tools"])
            break

    for script in section["scripts"]:
        fields = script_overrides.get(script["name"])
        if fields is None:
            continue
        matched.add(script["name"])
        if "purpose" in fields:
            _apply_cell(script, section["lines"], 1, fields["purpose"])

    return sorted((set(agent_overrides) | set(script_overrides)) - matched)


# --------------------------------------------------------------------------- #
# Derived values — every one counted from the parsed rows                      #
# --------------------------------------------------------------------------- #


def compute_summary(sections: list[dict]) -> tuple[list[tuple[str, int, int]], int, int]:
    """Per-section (label, agent count, script count) plus the two totals."""
    rows = [(s["label"], len(s["agents"]), len(s["scripts"])) for s in sections]
    return rows, sum(r[1] for r in rows), sum(r[2] for r in rows)


def compute_unique_tools(sections: list[dict]) -> list[str]:
    """Union of every Tools cell, in first-appearance order."""
    unique: list[str] = []
    for section in sections:
        for agent in section["agents"]:
            for tool in agent["tools"]:
                if tool not in unique:
                    unique.append(tool)
    return unique


def _agent_identities(sections: list[dict]) -> list[tuple[str, list[str]]]:
    """(display name, tools) for every agent row, in document order.

    The display name is the agent file stem plus its use case. When one file
    contributes several rows to the same section (an OrbConfig with several
    RunConfigs), the row's label disambiguates them.
    """
    identities = []
    for section in sections:
        stems = [Path(a["file"]).stem for a in section["agents"]]
        for agent, stem in zip(section["agents"], stems):
            name = stem if stems.count(stem) == 1 else f"{stem}:{agent['label']}"
            identities.append((f"{name} ({section['label']})", agent["tools"]))
    return identities


def compute_tool_set_overlaps(sections: list[dict]) -> list[tuple[list[str], list[str]]]:
    """Agents sharing an identical tool set, as (display tools, agent names).

    Grouping is by set equality — the report is about *sets*, so cell order does
    not split a group. Largest group first, ties broken by first appearance.
    """
    groups: dict[frozenset, dict] = {}

    for index, (name, tools) in enumerate(_agent_identities(sections)):
        if not tools:
            continue
        key = frozenset(tools)
        group = groups.setdefault(key, {"tools": tools, "agents": [], "first": index})
        group["agents"].append(name)

    shared = [g for g in groups.values() if len(g["agents"]) > 1]
    shared.sort(key=lambda g: (-len(g["agents"]), g["first"]))
    return [(g["tools"], g["agents"]) for g in shared]


def compute_script_overlaps(sections: list[dict]) -> list[tuple[str, list[str]]]:
    """Script names appearing in more than one section, sorted by name."""
    by_name: dict[str, list[str]] = {}

    for section in sections:
        for script in section["scripts"]:
            use_cases = by_name.setdefault(script["name"], [])
            if section["label"] not in use_cases:
                use_cases.append(section["label"])

    return sorted(
        ((name, use_cases) for name, use_cases in by_name.items() if len(use_cases) > 1),
        key=lambda pair: pair[0],
    )


# --------------------------------------------------------------------------- #
# Rendering                                                                    #
# --------------------------------------------------------------------------- #


def _code(values) -> str:
    return ", ".join(f"`{v}`" for v in values)


def render_matrix(sections: list[dict]) -> str:
    """Render the whole document: verbatim sections + the derived block."""
    summary_rows, total_agents, total_scripts = compute_summary(sections)
    tool_sets       = compute_tool_set_overlaps(sections)
    script_overlaps = compute_script_overlaps(sections)
    unique_tools    = compute_unique_tools(sections)

    parts = [TITLE, "", GENERATED_BY, ""]

    for section in sections:
        parts += ["---", "", "\n".join(section["lines"]).rstrip(), ""]

    parts += ["---", "", "## Overlap Report", "", "### Script name overlaps", ""]

    if script_overlaps:
        parts += ["| Script | Use cases |", "|--------|-----------|"]
        parts += [f"| {name} | {', '.join(use_cases)} |" for name, use_cases in script_overlaps]
    else:
        parts.append("No script name overlaps found.")
    parts += ["", "### Identical tool sets", ""]

    if tool_sets:
        parts += ["| Tools | Agents |", "|-------|--------|"]
        parts += [f"| {_code(tools)} | {', '.join(agents)} |" for tools, agents in tool_sets]
    else:
        parts.append("No identical tool sets found.")

    parts += [
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Use case | Agents | Scripts |",
        "|----------|--------|---------|",
    ]
    parts += [f"| {label} | {agents} | {scripts} |" for label, agents, scripts in summary_rows]
    parts += [
        f"| **Total** | **{total_agents}** | **{total_scripts}** |",
        "",
        f"**Unique tools across all use cases:** {_code(unique_tools)}",
        "",
    ]

    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Main                                                                         #
# --------------------------------------------------------------------------- #


def assemble(sections_dir: Path, output: Path, overrides_path: Path = OVERRIDES_JSON) -> int:
    """Assemble the matrix and write it. Returns the process exit code."""
    WARNINGS.clear()

    sections  = load_sections(sections_dir)
    overrides = load_overrides(overrides_path)
    unreadable_overrides = overrides is None
    overrides = overrides or {}

    unmatched: list[str] = []
    applied = 0

    for section in sections:
        if not section["present"]:
            continue  # already reported as missing; its overrides are not "stale"
        entry  = overrides.get(section["key"], {})
        offered = len(entry.get("agents", {})) + len(entry.get("scripts", {}))
        stale  = apply_overrides(section, overrides)
        unmatched += [f"{section['key']}.{key}" for key in stale]
        applied += offered - len(stale)

    for key in unmatched:
        _warn(f"override matches no row: {key} — curated text absent from the matrix")

    known = {key for key, _ in SECTIONS}
    for key in sorted(k for k in overrides if k not in known and not k.startswith("_")):
        _warn(f"override section not in SECTIONS, ignored: {key}")

    document = render_matrix(sections)

    try:
        output.write_text(document, encoding="utf-8")
    except OSError as exc:
        print(f"[FAIL] cannot write {output}: {exc}", file=sys.stderr)
        return 1

    _, total_agents, total_scripts = compute_summary(sections)
    missing = [s["key"] for s in sections if not s["present"]]

    print(
        f"Wrote {output} — {len(sections) - len(missing)}/{len(sections)} sections, "
        f"{total_agents} agents, {total_scripts} scripts, {applied} curated override(s) applied"
    )

    if missing:
        print(f"[FAIL] partial matrix — missing section(s): {', '.join(missing)}", file=sys.stderr)
        return 1

    if unmatched:
        print(
            f"[FAIL] {len(unmatched)} override(s) matched no row — curation silently dropped: "
            f"{', '.join(unmatched)}",
            file=sys.stderr,
        )
        return 1

    if unreadable_overrides:
        print(f"[FAIL] unreadable overrides file: {overrides_path}", file=sys.stderr)
        return 1

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--sections-dir", type=Path, default=SECTIONS_DIR, help="directory of {uc}.md section files"
    )
    parser.add_argument("--output", type=Path, default=OUTPUT_MD, help="matrix file to write")
    parser.add_argument(
        "--overrides", type=Path, default=OVERRIDES_JSON, help="curated-cell overrides JSON"
    )
    args = parser.parse_args()

    return assemble(args.sections_dir, args.output, args.overrides)


if __name__ == "__main__":
    sys.exit(main())
