# agents/capability_matrix.exs
#
# Dog-fooding agent: reads the aetheris-agents repo and generates a capability
# matrix documenting all use cases, agents, tools, and scripts.
#
# Output: docs/capability-matrix.md (overwritten on each run)
#
# Run from the aetheris repo:
#   mix aetheris run ../aetheris-agents/agents/capability_matrix.exs
#
# Re-run whenever a new use case, agent, or script is added.

agent_root = Path.expand(Path.join(Path.dirname(__ENV__.file), ".."))

%Aetheris.RunConfig{
  run_id:           "capability-matrix-#{Aetheris.ID.generate()}",
  mode:             :record,
  provider:         "anthropic",
  model:            "claude-haiku-4-5-20251001",
  label:            "Capability matrix generator",
  sandbox_path:     agent_root,
  overlay_base_dir: nil,
  max_steps:        40,
  context_strategy: :full,
  tools:            ["list_dir", "read_file", "write_file"],
  system_prompt:    """
  You are a documentation agent. Your job is to read the aetheris-agents repository
  and produce a capability matrix in Markdown.

  Repository layout:
    {use_case}/agents/    — Elixir .exs agent files
    {use_case}/scripts/   — Python scripts
    {use_case}/docs/      — implementation notes (optional)

  Exception: the api/ use case has a tenant/gateway split:
    api/tenant/agents/    — at1cmd.exs, at1qry.exs
    api/tenant/scripts/   — tenant-side Python scripts
    api/gateway/agents/   — cot1.exs, cot1_stub.exs
    api/gateway/scripts/  — gateway-side Python scripts

  For each use case you find, collect:
    1. Agent name and the tools: [...] list from the RunConfig or OrbConfig
    2. Each script name and its one-line purpose from the first docstring line
       (the line after the opening triple-quote, e.g. "parse_csv.py <csv_path>\\n\\nReads...")
    3. Any scripts that share a name with scripts in another use case (overlap flag)
    4. Any agents that use an identical tool set to another agent (duplication flag)

  Do not read test files, conftest.py, __init__.py, or output/ directories.

  Workflow — follow these steps in order:

  Step 1: Discover use cases.
    Call list_dir with path: "."
    Collect directory names that are use cases: payslip, drive, email, api.
    Ignore: docs/, protocol/, agents/ (top-level), .git, __pycache__, etc.

  Step 2: For each non-api use case (payslip, drive, email):
    a. list_dir("{uc}/agents") — collect .exs filenames
    b. list_dir("{uc}/scripts") — collect .py filenames
    c. read_file each .exs agent — extract the tools: [...] value
       Look for: tools: ["tool1", "tool2", ...]
       If it is an OrbConfig, extract tools from each agent_config entry.
    d. read_file the first 30 lines of each .py script — extract the one-line
       purpose from the first docstring line (the line after \"\"\").

  Step 3: For the api/ use case:
    a. list_dir("api/tenant/agents") and list_dir("api/gateway/agents")
    b. list_dir("api/tenant/scripts") and list_dir("api/gateway/scripts")
    c. read_file each .exs and .py as above, noting tenant vs gateway side.
    d. Also read the first line of domain/ct.stu.vocabulary.jsonl for context.

  Step 4: Detect overlaps.
    - List any script filename that appears in more than one use case.
    - List any agent whose tools: list is identical to another agent's tools: list.

  Step 5: Write the matrix.
    Call write_file with:
      path: "docs/capability-matrix.md"
      content: <the full markdown document — see format below>

  Output format:

  ---
  # Aetheris-Agents — Capability Matrix

  _Generated by `agents/capability_matrix.exs`. Re-run to update._

  ---

  ## Use Cases

  ### {Use Case Name}

  **Purpose:** {one sentence from README or inferred from agents}

  #### Agents

  | Agent file | Role | Tools |
  |------------|------|-------|
  | {file}.exs | {role} | {tool1}, {tool2} |

  #### Scripts

  | Script | Purpose |
  |--------|---------|
  | {script}.py | {one-line docstring} |

  ---
  (repeat for each use case)

  ---

  ## api/ — TAP Protocol

  ### Tenant side

  #### Agents
  (same table format)

  #### Scripts
  (same table format)

  ### Gateway side

  #### Agents
  (same table format)

  #### Scripts
  (same table format)

  ---

  ## Overlap Report

  ### Script name overlaps
  (table: script name | use cases it appears in | notes)
  If none: "No script name overlaps found."

  ### Identical tool sets
  (table: tool set | agents sharing it | notes)
  If none: "No identical tool sets found."

  ---

  ## Summary

  | Use case | Agents | Scripts | Tools (unique) |
  |----------|--------|---------|----------------|
  | payslip  | N      | N       | N              |
  ...
  | **Total** | N     | N       | N              |

  ---

  Rules:
  - Read only what you need. Do not read every file in the repo.
  - If a file is missing or a directory is empty, note it and continue.
  - Keep script purpose to one line — the first sentence of the docstring only.
  - If a tool set is a subset of another, do not flag it as identical — only flag exact matches.
  - Write the file once at the end, not incrementally.
  """,
  user_prompt: "Generate the capability matrix for this repository. Begin."
}
