# agents/capability_matrix_assemble.exs
#
# Orchestrator: assembles the capability matrix from section files written by
# the sub-agents in capability_matrix.exs.
#
# Run AFTER capability_matrix.exs completes:
#   mix aetheris run ../aetheris-agents/agents/capability_matrix.exs
#   mix aetheris run ../aetheris-agents/agents/capability_matrix_assemble.exs
#
# Reads:  docs/.sections/*.md  (written by sub-agents)
# Writes: docs/capability-matrix.md

agent_root = Path.expand(Path.join(Path.dirname(__ENV__.file), ".."))

%Aetheris.RunConfig{
  run_id:           "cap-matrix-assemble-#{Aetheris.ID.generate()}",
  mode:             :record,
  provider:         "anthropic",
  model:            "claude-haiku-4-5-20251001",
  label:            "cap-matrix: assembler",
  sandbox_path:     agent_root,
  overlay_base_dir: nil,
  max_steps:        15,
  context_strategy: :full,
  tools:            ["read_file", "write_file"],
  system_prompt:    """
  You are a documentation assembler. Section files have been written to
  docs/.sections/ by parallel sub-agents. Your job is to read those sections,
  detect overlaps, build a summary, and write the final capability matrix.

  Workflow — follow these steps in order:

  Step 1: Read all section files.
    Call read_file for each path:
      docs/.sections/payslip.md
      docs/.sections/drive.md
      docs/.sections/email.md
      docs/.sections/api_tenant.md
      docs/.sections/api_gateway.md
      docs/.sections/provenance.md
    If any file is missing, note it and continue.

  Step 2: Detect overlaps.
    From the section content:
    a. Script name overlaps: any .py filename appearing in more than one section.
    b. Identical tool sets: any two agents with exactly the same tools list.
       Subset matches do not count — only exact matches.

  Step 3: Build the summary table.
    Count agents and scripts per section.
    List all unique tools across all sections combined.

  Step 4: Write the final matrix.
    Call write_file with:
      path: "docs/capability-matrix.md"
      content: the assembled document (format below)

  Output format:

  # Aetheris-Agents — Capability Matrix

  _Generated by `agents/capability_matrix.exs`. Re-run to update._

  ---

  {paste docs/.sections/payslip.md content verbatim}

  ---

  {paste docs/.sections/drive.md content verbatim}

  ---

  {paste docs/.sections/email.md content verbatim}

  ---

  {paste docs/.sections/api_tenant.md content verbatim}

  {paste docs/.sections/api_gateway.md content verbatim}

  ---

  {paste docs/.sections/provenance.md content verbatim}

  ---

  ## Overlap Report

  ### Script name overlaps

  | Script | Use cases |
  |--------|-----------|
  | {script}.py | {uc1}, {uc2} |

  If none: "No script name overlaps found."

  ### Identical tool sets

  | Tools | Agents |
  |-------|--------|
  | {tool1}, {tool2} | {agent1}, {agent2} |

  If none: "No identical tool sets found."

  ---

  ## Summary

  | Use case | Agents | Scripts |
  |----------|--------|---------|
  | payslip  | N | N |
  | drive    | N | N |
  | email    | N | N |
  | api/tenant | N | N |
  | api/gateway | N | N |
  | provenance | N | N |
  | **Total** | N | N |

  **Unique tools across all use cases:** `tool1`, `tool2`, ...

  Rules:
  - Paste section content verbatim — do not summarise or reformat it.
  - If a section file is missing, write "Section not available." under that heading.
  - Write the output file once at Step 4.
  """,
  user_prompt: "Assemble the capability matrix from the section files. Begin."
}
